# Generated by Django 5.2.1 on 2025-05-25 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('produtos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_pedido', models.CharField(max_length=20, unique=True)),
                ('endereco_entrega', models.CharField(max_length=255)),
                ('forma_pagamento', models.CharField(choices=[('PIX', 'Pix'), ('CARTAO', 'Cartão'), ('BOLETO', 'Boleto')], default='PIX', max_length=10)),
                ('status_pagamento', models.CharField(choices=[('PENDENTE', 'Pendente'), ('APROVADO', 'Aprovado'), ('RECUSADO', 'Recusado')], default='PENDENTE', max_length=10)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('produtos', models.ManyToManyField(to='produtos.produto')),
            ],
        ),
    ]
